FROM python:3.12
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["sh", "-c", "python3 wait_for_db.py && python3 -m refresh_db && uvicorn main:app --host 0.0.0.0 --port 80"]