FROM python:3.12-slim

WORKDIR /app/

COPY requirements.txt ./

RUN apt-get update

COPY . .

RUN pip install --no-cache-dir -r ./requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/app"

EXPOSE 80

RUN chmod +x /app/startup.sh

CMD ["/bin/bash","-c", "./startup.sh"]