FROM python:3.12
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .  
RUN python3 -m refresh_db
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]