FROM python:3.12-slim

WORKDIR /app/

COPY requirements.txt ./

RUN apt-get update

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install psycopg2-binary

COPY . .

ENV PYTHONPATH "${PYTHONPATH}:/app"

EXPOSE 80

ENTRYPOINT [ "uvicorn" ]
CMD [ "main:app", "--host", "0.0.0.0", "--port", "80", "--reload" ]